//@version=6
strategy("S5_SuperTrend", overlay=true, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=10, commission_type=strategy.commission.percent, commission_value=0.1)
atrPeriod = 10
factor = 3.0
[supertrend, direction] = ta.supertrend(factor, atrPeriod)
plot(direction < 0 ? supertrend : na, color=color.green)
plot(direction > 0 ? supertrend : na, color=color.red)

if direction < 0 and direction[1] > 0
    strategy.entry("Long", strategy.long)
if direction > 0 and direction[1] < 0
    strategy.entry("Short", strategy.short)
